package com.example.database

import com.example.config.DatabaseSettings
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import java.sql.Connection

class DatabaseFactory(settings: DatabaseSettings) : AutoCloseable {
    private val dataSource = HikariDataSource(
        HikariConfig().apply {
            jdbcUrl = settings.url
            username = settings.user
            password = settings.password
            driverClassName = settings.driver
            maximumPoolSize = settings.maximumPoolSize
            isAutoCommit = true
        }
    )

    fun initialize() {
        connection { connection ->
            connection.createStatement().use { statement ->
                statement.executeUpdate(
                    """
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login VARCHAR(100) NOT NULL UNIQUE,
                        password_hash VARCHAR(255) NOT NULL,
                        role VARCHAR(20) NOT NULL
                    )
                    """.trimIndent()
                )

                statement.executeUpdate(
                    """
                    CREATE TABLE IF NOT EXISTS books (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        author VARCHAR(255) NOT NULL,
                        publication_year INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
            }
        }
    }

    fun <T> connection(block: (Connection) -> T): T =
        dataSource.connection.use(block)

    override fun close() {
        dataSource.close()
    }
}
